# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
# https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         args:
#             [
#                 "--rcfile=pylintrc", # Link to your config file
#                 # "--errors-only", # Add this option just to pre-commit
#             ]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.942'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-requests==2.27.15]
#         # args: [--no-strict-optional, --ignore-missing-imports]
